### ISSUE TITLE
Issues with julia 0.5.0 and latest GLvisualize

### ISSUE THREAD

**Issue by fanoux** [SimonDanisch/SchroedingersSmoke.jl#1]
Hi,

I am a newbie to Julia
But using the latest GLvisualize, there is a keyword error with view.
I tried to dodge by changing to 
`vis = visualize(
        (Circle(Point2f0(0), 0.006f0), (Float32[0], Float32[0], Float32[0])),
        billboard=true
    )`
`_view(vis,w,camera = :perspective)`
Then there is nothing displayed at all in the viewport.
Many times at runtime the following message is displayed
`WARNING: sub is deprecated, use view instead.
 in depwarn(::String, ::Symbol) at .\deprecated.jl:64
 in sub(::Array{Complex{Float64},3}, ::Vararg{Any,N}) at .\deprecated.jl:30
 in VelocityOneForm(::SchroedingersSmoke.ISF, ::Array{Complex{Float64},3}, ::Array{Complex{Float64},3}, ::Float64) at C:\Users\User\.julia\v0.5\SchroedingersSmoke\src\ISF.jl:102
 in PressureProject(::SchroedingersSmoke.ISF, ::Array{Complex{Float64},3}, ::Array{Complex{Float64},3}) at C:\Users\User\.julia\v0.5\SchroedingersSmoke\src\ISF.jl:80
 in macro expansion; at C:\Users\User\CloudStation\SchroedingersSmoke.jl-sd-noacc\examples\sle_example_jet.jl:108 [inlined]
 in anonymous at .\<missing>:?
 in include_from_node1(::String) at .\loading.jl:488
 in process_options(::Base.JLOptions) at .\client.jl:262
 in _start() at .\client.jl:318
while loading C:\Users\User\CloudStation\SchroedingersSmoke.jl-sd-noacc\examples\sle_example_jet.jl, in expression starting on line 101`

**Comment by SimonDanisch** [comment]
Sorry, I have dropped this project for some time. Let me take the chance to patch things up, hopefully today!!

**Comment by SimonDanisch** [comment]
I just [tagged a first working version](https://github.com/JuliaLang/METADATA.jl/pull/12396) and added some notes to the readme :)
